apiVersion: v1
kind: Namespace
metadata:
  name: mk-sentiment-streamlit-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mk-sentiment-streamlit
  namespace: mk-sentiment-streamlit-ns
spec:
  replicas: 5
  selector:
    matchLabels:
      app: mk-sentiment-streamlit
  template:
    metadata:
      labels:
        app: mk-sentiment-streamlit

    spec:
      containers:
        - name: mk-sentiment-streamlit
          image: anixdrone/mk-sentiment-streamlit
          imagePullPolicy: Always
          ports:
            - containerPort: 8501
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mk-sentiment-streamlit-service
  namespace: mk-sentiment-streamlit-ns
spec:
  type: ClusterIP
  ports:
    - port: 8501
  selector:
    app: mk-sentiment-streamlit
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mk-sentiment-streamlit-ingress
  namespace: mk-sentiment-streamlit-ns
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"

spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: mk-sentiment-streamlit-service
                port:
                  number: 8501
            path: /
            pathType: Prefix