apiVersion: apps/v1
kind: Deployment
metadata:
  name: mk-sentiment-streamlit

spec:
  replicas: 5
  selector:
    matchLabels:
      app: mk-sentiment-streamlit
  template:
    metadata:
      labels:
        app: mk-sentiment-streamlit

    spec:
      containers:
        - name: mk-sentiment-streamlit
          image: anixdrone/mk-sentiment-streamlit
          imagePullPolicy: Always
          ports:
            - containerPort: 8501
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mk-sentiment-streamlit-service
spec:
  type: ClusterIP
  ports:
    - port: 8501
  selector:
    app: mk-sentiment-streamlit